version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - setup_docker_engine

      - run:
          name: API Unit and Integration Tests
          command: mvn clean verify -f api/pom.xml

      - run:
          name: API jar Build
          command: mvn clean install -f api/pom.xml -Dmaven.test.skip=true

      - run:
          name: UI Build
          command: mvn clean package -f ui/pom.xml -Dmaven.test.skip=true

      - run:
          name: Build Docker Image
          command: docker build -t local-tomcat .

      - run:
          name: Run Docker Container
          command: |
              docker run -d -p 8080:8080 local-tomcat &&
              sleep 10 &&
              docker ps &&
              sudo apt-get install traceroute &&
              export HOSTNAME=localhost &&
              ping -c 10 $HOSTNAME > $CIRCLE_ARTIFACTS/network-report.log &&
              traceroute $HOSTNAME >> $CIRCLE_ARTIFACTS/network-report.log &&
              curl --retry 10 --retry-delay 5 -v http://localhost:8080

      - run:
          name: Acceptance Tests
          command: mvn clean test -f acceptance-test/pom.xml -Drest.url=http://localhost:8080/todolist

      - run:
          name: Stop Docker Container
          command: docker stop $(docker ps -a -q)